server:
    port: 8001

druid:
    type: com.alibaba.druid.pool.DruidDataSource
    study:
      master: #study库的主库
        url: jdbc:mysql://localhost:3306/ttt_ds1?useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
      slave: #study库的从库
        url: jdbc:mysql://localhost:3306/ttt_ds1_s?useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
    product:
      master: #product库的主库
        url: jdbc:mysql://localhost:3306/ttt_ds2?useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
      slave: #product库的从库
        url: jdbc:mysql://localhost:3306/ttt_ds2_s?useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
mybatis:
  type-aliases-package: com.ttt.dynamic.datasource.dao.entity


