spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis: 
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.ttt.quartz.persistence.entity
    