server:
    port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ttt.demo.boottest.entity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ttt_ds1?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
